name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1', '1.7']
        julia-arch: [x64, x86]

    steps:
      - name: checkout tiled
        uses: actions/checkout@v3
        with:
          repository: 'bluesky/tiled.git'
          fetch-depth: '0'
          path: 'tiled-server'

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: install tiled
        run: python -m pip install ./tiled-server/tiled

      - name: start tiled
        run: ALICE_PASSWORD=secret1 BOB_PASSWORD=secret2 CARA_PASSWORD=secret3 tiled serve config ./tiled-server/tiled/example_configs/toy_authentication.yml &

      - uses: actions/checkout@v2

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1